### ISSUE TITLE
Cool， so why not have typescript supported？

### ISSUE THREAD

**Issue by yanlee26** [use-global-hook/use-global-hook#12]

**Comment by MGItkin** [comment]
+1 but, I'm not experienced enough in TS to create the definitions and I couldn't get the auto-generator to work. Any advice on a path forward?

**Comment by yanlee26** [comment]
https://medium.com

**Comment by nmccready** [comment]
Supported here . Same code but fully typed with some extensions and fixes.

https://github.com/nmccready/use-global-hook

**Comment by nmccready** [comment]
I'd make a PR back to here if it would be accepted in a reasonable about of time. I had old outstanding PRs which took very long. This is why I have run w/ my own fork.

**Comment by andregardi** [comment]
Nice @nmccready 
But I would prefer to not change the whole code to typescript.
If someone could create a definitions type file (.d.ts), would be great!

**Comment by nmccready** [comment]
Right I used to be just like you and holding out against typescript. But this project really is perfect for it as its a very small project which is easy to get used to for typescript itself.

 I was managing the type definitions separate  from the code base as you suggest. This actually turned out to be a major pain where the TS interface did not really match what the real code was doing.

It wasn't until I made it fully typescript with unit tests where I was able to correctly flush out the definitions for what they are.

So to reiterate here, I think this would be going black-wards and cause more pain in the future.

**Comment by nmccready** [comment]
Also the type definitions are extremely useful in other projects to clearly see what your interacting with.

**Comment by ojameso** [comment]
Really neat and needed the functionality for a project I'm working on so I wrote my own `use-global-hook.d.ts`. It's been working for me. Any improvements or suggestions to this would be greatly appreciated.

```
// src/use-global-hook.d.ts
declare module 'use-global-hook' {
  import React from 'react';

  // Where S is typeof state and A is typeof associated actions
  export interface Store<S, A> {
    state: S;
    actions: A;
    setState: (state: S, afterUpdateCallback?: () => void) => void;
    // listener is meant to be internal, so no public interface
  }

  export type InitializerFunction<S, A> = (store: Store<S, A>) => void;

  export default function useStore<S, A>(React: React, inititalState: S, actions: object, initializers?: InitializerFunction<S, A>): () => [S, A];
}
```

It would be great if the associated actions could be inferred, but since the functions are bound and actions could have a tree, it's tough to write a generic for it.
Would be used as such...
```
// src/actions
import { Store } from 'use-global-hook';
export const setValue = (
  store: Store<State, AssociatedActions>,
  value: string
) => {
  store.setState({ ...store.state, value });
  store.actions.otherAction(true);
};

// src/hook
export default useStore<State, AssociatedActions>(
  React,
  initialState,
  actions
);

// src/type
type AssociatedActions = {
  setValue: (value: string) => void
  otherAction: (other: boolean) => void
};

type State = {
  value: string
}
```

**Comment by DanielRuf** [comment]
Would be great to have the PR(s) to get the changes.

**Comment by ojameso** [comment]
I'd be more than happy to add the above type definition to definitely typed and then post a pr here to add instructions for typescript users on the README. If @andregardi is ok with that.

**Comment by DanielRuf** [comment]
Sure, why should he not be ok with it?

**Comment by andregardi** [comment]
Hello @ojameso 
I would love to see a pull request with yours files.
Thank you for taking interest on the project.

**Comment by ojameso** [comment]
@DanielRuf @yanlee26 @MGItkin Typescript now supported. Refer to the PR above. But basically, `npm install --dev @types/use-global-hook`. And use the `Store` interface provided by the type definition. Details on how to use are now on the README.md.

**Comment by ieow** [comment]
Having React Type error when trying to use typescript.
Is it fixed React version needed to run this library?
Shouldn't it be more flexible ?

Error:
Argument of type 'typeof React' is not assignable to parameter of type 'typeof React'.
  Types of property 'lazy' are incompatible.
    Type '<T extends React.ComponentType<any>>(factory: () => Promise<{ default: T; }>) => React.LazyExoticComponent<T>' is not assignable to type '<T extends import("/home/apollo/Desktop/rain/echoss/stamp_roulette/node_modules/@types/react-dom/node_modules/@types/react/index").ComponentType<any>>(factory: () => Promise<{ default: T; }>) => import("/home/apollo/Desktop/rain/echoss/stamp_roulette/node_modules/@types/react-dom/node_modules/@types/react/index").La...'.

**Comment by DanielRuf** [comment]
@ieow please create a new issue and provide all relevant details (your TypeScript and `tsc` version, a reproducible testcase and so on).

**Comment by ojameso** [comment]
@ieow agreed with @DanielRuf but did open a [new pr with DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39199) that I think will address the issue as well as incorporate a better type def so we don't have to include the expected types. Much cleaner usage.

**Comment by DaveClissold** [comment]
I am getting an odd ts error 
```
Argument of type '(actions: SearchActions) => (value: string) => void' is not assignable to parameter of type '(state: unknown) => (value: string) => void'.
  Types of parameters 'actions' and 'state' are incompatible.
    Type 'unknown' is not assignable to type 'SearchActions'
```

when trying to use a subset of the state with the following 
```
 const [productCategory, setProductCategory] = useSearch<
    string,
    (value: string) => void
  >(
    (state: SearchState) => state.productCategory,
    (actions: SearchActions) => actions.setProductCategory
  );
```

**Comment by ojameso** [comment]
@DaveClissold I think the docs on using TS is outdated. If you have the latest TS definitions from definitelyTyped, you do not have to pass in the types expected. So you can write...
```
 const [productCategory, setProductCategory] = useSearch(
    state => state.productCategory,
    actions => actions.setProductCategory
  );
```

**Comment by DaveClissold** [comment]
@ojameso When I try the above I get `Object is of type 'unknown'` for actions. Any ideas?

**Comment by ojameso** [comment]
@DaveClissold do you have the latest type definitions?

**Comment by DaveClissold** [comment]
@ojameso I assume I am. They should be version 0.1.2 correct, committed on 23 October 2019?  When I check the repository, the comment at the top reads the following.

```// Type definitions for use-global-hook 0.1```

[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/use-global-hook/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/use-global-hook/index.d.ts)
