### ISSUE TITLE
Can here fn.call be used? cause it seems hard to understand..

### ISSUE THREAD

**Issue by yanlee26** [use-global-hook/use-global-hook#13]
https://github.com/andregardi/use-global-hook/blob/355f1d8a83a0b2ff20081a25a3fb3e455c50ce41/index.js#L23

**Comment by yanlee26** [comment]
seems cannot. While I think there exist better way.

**Comment by andregardi** [comment]
Yep,
fn.call would be more execute the function rather than bind the parameters.
