### ISSUE TITLE
Bug: Race conditions

### ISSUE THREAD

**Issue by nmccready** [use-global-hook/use-global-hook#14]
I have seen several race conditions present themselves when either racing to register a listener or deregistering a listener. In these cases a listener may miss an update and or the listener function may be even missing all together.

See this example https://codepen.io/nmccready/pen/vYBgrGR

```
 // interesting race condition
      // delaying set so the Consumer has time to register listener
      // note setState would work if we do, `setState({ ref: r });`
      setTimeout(() => {
        setRef(r);
        setState(r);
      }, 500);
```
Remove the `setTimeout` and you will see the Consumer will miss and never get any updates to the state.

As far as a workaround to prevent against listeners that are no longer there I added this line.

https://github.com/nmccready/use-global-hook/blob/master/src/index.ts#L58

To me this begs the question of the store's design and if it should be moved to be immutable and not use `this` at all.

Would love some thoughts on this.

**Comment by andregardi** [comment]
Yes, interesting conditions you got there.

For the readers with difficult to understand the nmccready conde:
In this example, he is using a forked version of the library.

@nmccready 
Combining the reference callback inside the useMemo hook rendering it at the same level of the consumer created a very particular condition.

To better understand the problem we need to, first understand that:
1 - The custom hook uses the useEffect to push the listener to the list.
2 - The useEffect runs after the component mount, not before.

In your example, all the components are mounted, then, the ref callback function is started before the useEffect inside the custom hook. In an practical way, you changed the state after the consumer read the state, but before it subscribes to changes.

How do we fix it?
I will add another condition inside the useEffect to run the new listener if the state has been changed during this time.

**Comment by nmccready** [comment]
Sounds like a solid plan :)

**Comment by andregardi** [comment]
Version 0.1.8 released - bug fixed.
Check line 14

https://github.com/andregardi/use-global-hook/blob/f6a58c774364b7231601518d0d8dd1ee8ace6163/index.js#L14

I took the opportunity to remove the use of "this".

**Comment by nmccready** [comment]
Nice
