### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by subhendukundu** [use-global-hook/use-global-hook#16]
Is there a chance of `store.listeners[i]` can be undefined at anytime from the below code, using the latest version?
```
for (let i = 0; i < listenersLength; i++) {
    store.listeners[i].run(store.state);
}
```
I am calling the globalaction aomething like this
```
globalActions.setSignedupUser({
      newUser: false,
      user: {
        displayName: name, email: userEmail, photoURL, phoneNumber, uid
      }
});
```
and in my actions
```
export const setSignedupUser = (store, data) => {
  store.setState({ ...data });
};
```
It will be very helpful to know your thoughts on this.

**Comment by andregardi** [comment]
Hello @subhendukundu 
It is a possibility.
I think there is nothing wrong with the way you are calling the library.
Can you share a sandbox (like https://codesandbox.io/) with a reprosusable version of the problem?

Alternative approach:
You can also open the package file, inside the node_modules, replace the **for** for a **foreach**. 

```
for (let i = 0; i < listenersLength; i++) {
    store.listeners[i].run(store.state);
}
```

To

```
store.listeners.forEach((listener) => {
    listener.run(store.state);
  });
```

If that works, I will create a new release with this changes.
Or, if you have the time, make a pull request and I will accept it.

Let me know if it works for you.

**Comment by subhendukundu** [comment]
Yes, you are right, that fixed the issue.
I added a PR. [#17](https://github.com/andregardi/use-global-hook/pull/17)

**Comment by andregardi** [comment]
Thank you @subhendukundu 
Version 0.1.11 released.
