### ISSUE TITLE
React Hook "useGlobalHook" cannot be called at the top level

### ISSUE THREAD

**Issue by cywtf** [use-global-hook/use-global-hook#20]
Newer versions of react-scripts that includes `eslint-plugin-react-hooks` directly will not allow calling `const useGlobal = useGlobalHook(React, initialState, actions)` outside of a function component.

The linter will throw an error:
> React Hook "useGlobalHook" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks

How would you refactor any of your examples to comply to this particular rule of Hooks?
Something as the Minimal example in the [npm package](https://www.npmjs.com/package/use-global-hook) will break in these newer versions.

**Comment by andregardi** [comment]
@rootion 
For now, we can adjust it changing the name of the import:

import globalHook from 'use-global-hook'; 
const useGlobal = globalHook(React, initialState, actions);

The globalHook itself doesn't call any hook,so it is safe to use on the top level.
Bealive or not, this lint rule is not really looking if we have a hook inside the function.
It is only checking if the function starts with the word "use"! I was not expecting for that.

**Comment by cywtf** [comment]
Thank you for the answer, I didn't know that a simple rename could shut up the linter. 
If the globalHook itself doesn't call any hook at the top level, then it doesn't break any rule of hooks.
