### ISSUE TITLE
Double render on react-native

### ISSUE THREAD

**Issue by NicholasBertazzon** [use-global-hook/use-global-hook#23]
Hi, 
First or all, thanks a lot for your work.
Do you experience a double render instead of one in react-native? With other hooks, like useState, I get one render, but with this, I get another render out of nowhere. 
**It happens only when the component is being mount the first time, in every single component.**
Also, if you use 2/3/4/X of your hooks in the component, it doesn't matter. It still render two times.

```
import React from "react";
import { AppRegistry, View } from 'react-native';
import App from './app/App';
import { name as appName } from './app.json';
import { useSettings } from "./app/store";

AppRegistry.registerComponent(appName, () => function(){
    const [, setTheme] = useSettings(
        state => undefined,
        actions => actions.setTheme
    );
    console.log("render");
    return <View></View>;
});
```

You can test it even on the index.js of a the project (my useSettings hook is almost the same of your useGlobal example).

Is it normal? Because I tried it on React and it seems to not double render.

Thanks,
Nicholas Bertazzon.

**Comment by nmccready** [comment]
Did you try wrapping any of this in `useMemo` to see if that might help?

**Comment by nodtem66** [comment]
Hi @NicholasBertazzon @nmccready 
I've found this too, see in https://codesandbox.io/s/4h3n3

After digging for an hour, I proposed the solution as see in `store/use-global-hook.js`.
Change the `React.useState(Object.create(null));` to `React.useState(state);`.

Let's see the effect by comment Line 2 and uncomment Line 4 in `store/index.js`
Cheers

**Comment by nmccready** [comment]
@nodtem66 nice work, that should be a PR I can see how it would double render now as the original hooks default state would not have been the original state. Therefore, it would immediately update. I'd make a PR.

**Comment by itsam** [comment]
@nodtem66 , @nmccready , @andregardi 
Indeed there's a double rendering in React Native and the above solution works nicely, but the real difference is made by commenting out 
```
//newListener.run(store.state);
```

**Comment by pprimm** [comment]
I believe I see an "initial double-render" when the component is mounted in React.  I took the "Avoid unnecessary renders" codesandbox example and removed `<h3>{renderTime()}</h3>` from `<App />` and changed `renderTime()` to:
```
...
  const currentTime = new Date().toLocaleTimeString();
  console.log(`render @ ${currentTime}`);
  return (
...
```
I get two (2) log entries when a component is added and only one entry for each component when a counter is incremented.  [https://codesandbox.io/s/several-counters-double-render-example-wzvkp](https://codesandbox.io/s/several-counters-double-render-example-wzvkp)
Same behavior for 0.1.12 & 0.1.11
