### ISSUE TITLE
Comunication between stores

### ISSUE THREAD

**Issue by abdelav** [use-global-hook/use-global-hook#24]
What is the proper way to communicate between two stores, for example, get the email from the user store state to mailer store?

**Comment by andregardi** [comment]
@abdelav 
Actually, you supposed to have only one store, with the whole state. If you have difficult to manage all your data, remember that you can split your actions on several files. You can nest it in as many level you want. See the example:
https://codesandbox.io/s/wqvykj5497

Does that help you?
