### ISSUE TITLE
Add Example(s) for Non-Monolithic Application Designs

### ISSUE THREAD

**Issue by jminnihan** [use-global-hook/use-global-hook#26]
Great concept, poor real-world examples. Most SPA applications are non-monolithic in design, containing many features, each with their own states and actions. It would be a "good thing" to assist developers in developing an model example application containing at least two features and show how each feature defines their own global hooks, scopes and actions and then composites each of the feature hooks into a single global hook, scope and list of actions.

**Comment by lveillard** [comment]
I came looking for this. My store.js is too big and I would love to divide it in some pieces :)

**Comment by andregardi** [comment]
You supposed to have a single store with all your data, like redux. You can split your actions in several files, nested in as many levels you want.

@lveillard 
If your store.js is too big, you are trying to declare all your actions or a big initial state in one file only. 
If you share an example of what you are doing, I can try to help you to split the files.

In short,
1 - you can split your actions in several files using the following example:
https://codesandbox.io/s/wqvykj5497

2 - the initial state is a static file, you can split its construction in any way you want.

Does that help you guys?

**Comment by lveillard** [comment]
Yay! awesome! thank you i was just including all the actions in the same file :)
Maybe sharing that example on the doc would be a good idea for noobs like me

Thank you for the help!
