### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by patyiscoding** [use-global-hook/use-global-hook#27]
Language used: Typescript

I'm getting `SyntaxError: Unexpected token export` at `module.exports = require("use-global-hook");`. Should I add something to my babel configuration in order for the global hook to work?

**Comment by ddubson** [comment]
Having the same issue when running Jest (using ts-jest transformer).

Here's the error:

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

   /[my-project]/node_modules/use-global-hook/index.js:61
    export default useStore;
```

**Comment by jotty-mcclure** [comment]
I'm seeing the same issue, but it only occurs when I refresh the page.

**Comment by andregardi** [comment]
Guys, I am no TS expert.
Maybe I take some time to check it out soon. But, if anyone, have a tip on it, I would appreciate it.

**Comment by ddubson** [comment]
My guess is the issue comes from `export default useStore` statement at the end of `index.js` published artifact. In my project, I replaced `export default useStore` with older ES5 syntax `module.exports = useStore;` and it started working.

**Comment by BilalQadri** [comment]
> My guess is the issue comes from `export default useStore` statement at the end of `index.js` published artifact. In my project, I replaced `export default useStore` with older ES5 syntax `module.exports = useStore;` and it started working.

thanks

**Comment by yanfeix** [comment]
Hi @andregardi, when are you gonna release the fix on https://www.npmjs.com/package/use-global-hook? I have run into this issue as well, and blocked on the unit-test.

**Comment by tillkolter** [comment]
Is this project still maintained?
