### ISSUE TITLE
How could I get a chance to access other hooks?

### ISSUE THREAD

**Issue by siwei-lu** [use-global-hook/use-global-hook#28]
I'm trying to push a new history after an asynchronous action done, hence I have to use `useHistory` hook from `react-router-dom`.

How could I?

**Comment by andregardi** [comment]
@IdanLoo 
It is a little hard to help without an example.
Maybe, for example, you could extract "goBack" from the useHistory and send it as a parameter to your action and call it there.

Does that help you?

**Comment by siwei-lu** [comment]
Thx. It helps.
