### ISSUE TITLE
Where is the best place to fetch initial data? 

### ISSUE THREAD

**Issue by jfuenmayor96** [use-global-hook/use-global-hook#3]
Right now I am doing a project refactor. One of the changes we want to introduce is the use of a global state without using Redux. At first I tried using React Context but I saw your article on Medium and I liked how you managed to organize and modularize the actions and everything.

With React Context I could use a `fetchInfo()` method in the `componentDidMount()` method of the `ContextProvider` to fetch all the information needed and update the default dummy state, but I cannot figure out a way to do the same thing using your package, this is my first time using Hooks though. 

Any suggestions?

**Comment by andregardi** [comment]
@jfuenmayor96 
Just for you, my friend, I published on npm the 0.1.7 version.
Now, it accepts a fourth parameter which allows us to do this:

```javascript
import React from "react";
import useGlobalHook from "use-global-hook";

import * as actions from "../actions";

const initialState = {
  counters: {
    requests: 0,
    success: 0,
    fail: 0
  },
  status: "INITIAL",
  repos: []
};

const initializer = store => {
  store.actions.github.getReposByUsername("jfuenmayor96");
};

const useGlobal = useGlobalHook(React, initialState, actions, initializer);

export default useGlobal;
```

Checkout the full example in sandbox:
https://codesandbox.io/s/lxk5om3k0m
