### ISSUE TITLE
Problem when use Animated.value

### ISSUE THREAD

**Issue by adonisdoda** [use-global-hook/use-global-hook#37]
Hello my friend, first of all...Good Work with this library, i use much and love like is simple.
I discover the issue in my project for example, when i set an state with a animated value (new Animated.value) for any reason if I unmounted the component and reset the state (seting initial state) this value not 'reset', i need force reset for work.
What can this be?
![image](https://user-images.githubusercontent.com/33674001/73811006-02377e80-47b7-11ea-8a83-989122c8d8fc.png)
![image](https://user-images.githubusercontent.com/33674001/73811031-124f5e00-47b7-11ea-9c9d-ca13d349d631.png)

Look, I reset the state in INITIAL_STATE and change the value in INITIAL_ANIMATION...
For the animated value i need force the inital state

**Comment by andregardi** [comment]
@adonisdoda 
The AnimatedLocalComponent inside the initialState is passed as reference. So, you have the same instance of Animate inside your  store.state and your initialState object. When you call store.setState(initialState) it is actually work, but your initialState.AnimatedLocalComponent was manipulated.

You will have the same problem with any object that its methods manipulates its internal values.

If you want to use the initialState more than one time I would recomend to change it to a function that returns a fresh object.

```
const initialState = () => {
    return {
        eventName: '',
        ...
        AnimatedLocalComponent: new Animate.Value()
    }
}
 
store.setState(initialState())
```

**Comment by adonisdoda** [comment]
Oh tnks for response .
It's worked for me.
