### ISSUE TITLE
Duplicate rendering?

### ISSUE THREAD

**Issue by huy23121994** [use-global-hook/use-global-hook#48]
I just test a simple code as below, and I don't understand my component render twice if the state is changed?
Is this bug or ... feature?

![image](https://user-images.githubusercontent.com/9770074/87655216-2645b580-c782-11ea-8c60-77fa4bbb2ca0.png)

![image](https://user-images.githubusercontent.com/9770074/87655246-32317780-c782-11ea-9dd3-cdc84cc60deb.png)

In browser console

![image](https://user-images.githubusercontent.com/9770074/87661795-71b09180-c78b-11ea-9b0a-29cf92539c05.png)

**Comment by huy23121994** [comment]
btw, when use `npm i use-global-hook`, It will install v0.1.12 by default, with above problem, User component rerender 4 times

**Comment by nodtem66** [comment]
@s-KaiNet proposed two solutions. Let's try them.
https://github.com/andregardi/use-global-hook/pull/25

> Will it be safer just use const newListener = { oldState: state }; on line [18](https://github.com/andregardi/use-global-hook/blob/master/index.js#L18)?
> Alternatively, can we just remove [this line](https://github.com/andregardi/use-global-hook/blob/master/index.js#L29), because it causes to double render?

**Comment by Maxoos** [comment]
I think this is a duplicate of [https://github.com/andregardi/use-global-hook/issues/23](url)

**Comment by nodtem66** [comment]
@huy23121994 
I suspected the double-rendering from #25 and [double-rendering from React.StrictMode](https://mariosfakiolas.com/blog/my-react-components-render-twice-and-drive-me-crazy/), used in default `index.js` of `create-react-app`

See [my codesandbox](https://codesandbox.io/s/use-global-hook-48-x9xl3?file=/src/index.js)

**Comment by huy23121994** [comment]
Understood, thanks man @nodtem66
