### ISSUE TITLE
avoid unnecessary renders does not work when selecting multiple state values.

### ISSUE THREAD

**Issue by lneir-plenty** [use-global-hook/use-global-hook#63]
The example: https://codesandbox.io/s/several-counters-pdbsy avoids unnecessary renders correctly but if multiple state items are selected in the mapState function then the render still occurs... 

For example, in the forked example, (https://codesandbox.io/s/several-counters-bug-c-updates-ab-ldltx?file=/src/index.js) CounterAB selects both A and B state. When counter C is incremented then CounterAB gets re-rendered. Ideally incrementing C should not cause re-render to CounterAB.

The reason this happens is because mapState returns a new object and the code here https://github.com/andregardi/use-global-hook/blob/master/src/core/newListenerEffect.js#L8 checks that the references are equal - which of course they won't be.

One way to fix this is to allow an optional equality function to be passed in the options. This is similar to what is done in redux for "useSelector": https://react-redux.js.org/api/hooks#useselector.

**Comment by davityavryan** [comment]
should be fixed now.
