### ISSUE TITLE
Is is maintained?

### ISSUE THREAD

**Issue by davityavryan** [use-global-hook/use-global-hook#66]
@andregardi
Seems like you stoped working on this. :/
https://isitmaintained.com/project/andregardi/use-global-hook 

Should we fork?

**Comment by codthing** [comment]
@davityavryan 
@andregardi does not seem to be very active, I support your fork.

**Comment by davityavryan** [comment]
;(
I just don't want to create another version of this. I understand that we might need to. But npm is already a zoo of packages.

Let's give him a week or so. if he will not respond then I might fork it and convert to TS

p.s. there is also another one https://www.npmjs.com/package/use-global-hook-ts seems to be a fork which is not maintained either. :(

**Comment by andregardi** [comment]
Hey @davityavryan 
Thank you for keep up with this project.

I have an ideia, maybe it is time to add more people as owners of this, starting with you.
I am going to look into the best way to we share the npm ownership and github repo.

**Comment by davityavryan** [comment]
Hey @andregardi 

It would be an honour for me. Thanks a lot.

I need a short chat with you just so that we will be on same page. I need to understand what it means for me in terms of responsibilities.
Can you setup https://gitter.im/ for `use-global-hook`? So that we can discuss privately (also it will be a benefit for the package, as of we will be more open for everyone). Just signal me here, I will join channel.

**Comment by davityavryan** [comment]
@andregardi can you please release master or give me access? I merged https://github.com/andregardi/use-global-hook/pull/61

please consider Gitter so that we can chat privately

**Comment by andregardi** [comment]
@davityavryan 
I transferred the repo to a collaborative github corporation and set you as admin.
Tell me if that is working for you.

I added you to Gitter two days ago, also check that, please.

**Comment by davityavryan** [comment]
All good. Thanks a lot. see you in Gitter. ;)
